### ISSUE TITLE
GS Plugin installer scripts are loaded on all pages

### ISSUE THREAD

**Issue by webketje** [HelgeSverre/gs-plugin-installer#9]
Which ofc. leads to JS errors & useless asset loading

**Comment by HelgeSverre** [comment]
Nice catch, I thought registering and queuing the scripts only loaded it for the specific plugin page, please create a PR with this fix :)

**Comment by webketje** [comment]
I reassure you, the only reason I was looking into this is because I came across the same problem for GS Custom Settings :)

**Comment by HelgeSverre** [comment]
Fixed in https://github.com/HelgeSverre/gs-plugin-installer/commit/0186c85e937012cc52d8a3205bdd063d0afee648
